### ISSUE TITLE
side-by-side layout

### ISSUE THREAD

**Issue by slaurent22** [slaurent22/hk-split-maker#10]
I'm imagining the input and output side-by-side. I'd like to see the input text area with submit button have the same relative layout as the output text area with download button (whether both above or both below)

```
[ ----- Title Region ------ ]
[ ----- Instructions ------ ]
Input Config | Output Splits File
[text area]  | [text area]
[text area]  | [text area]
[text area]  | [text area]
[text area]  | [text area]
[submit]     | [download]

**Comment by afif1400** [comment]
Can I work on this

**Comment by slaurent22** [comment]
> Can I work on this

We already have #12 and #13 which both address this. After those are settled, feel free to propose more ideas. You may want to discuss with @rixx who I believe has more ideas in the works

**Comment by afif1400** [comment]
> We already 
Yeah np

**Comment by rixx** [comment]
> You may want to discuss with @rixx who I believe has more ideas in the works

@afif1400 feel free to ping me on discord at rixx#9655 or here

**Comment by afif1400** [comment]
Okay.....but are issues #12 and #13  resolved?

**Comment by afif1400** [comment]
> Okay.....but are issues #12 and #13 resolved?

Coz its not merged yet

**Comment by slaurent22** [comment]
@afif1400 rixx is offering to chat while the PRs are still open

**Comment by afif1400** [comment]
> @afif1400 rixx is offering to chat while the PRs are still open

Oh... okay

**Comment by slaurent22** [comment]
Closing with https://github.com/slaurent22/hk-split-maker/pull/12 which is now live. I'll create a new issue for further enhancements
