### ISSUE TITLE
Feature request: Import splits file

### ISSUE THREAD

**Issue by AlexKnauth** [slaurent22/hk-split-maker#133]
It would be nice if there were a button to import an existing splits file to use as a preset configuration to start from. Doesn't have to preserve the times, just the split names and the auto-splitter settings would be wonderful.

**Comment by slaurent22** [comment]
this has been in the back of my mind for a while. It'll definitely happen, it's just a matter of when I get around to it

**Comment by AlexKnauth** [comment]
I'm putting my work so far on an `import` branch here:
https://github.com/AlexKnauth/hk-split-maker/tree/import

It's not ready yet, but once it is, I can make a PR.
