### ISSUE TITLE
Make it easier to change split names

### ISSUE THREAD

**Issue by flibber-hk** [slaurent22/hk-split-maker#21]
Use case: adding cheater notes to split names - the obvious thing is things like [3D] to indicate a stag instruction, or [24] to indicate the number of levers hit / rocks broken / etc by/in that split. Perhaps allow the user to type e.g. "BlackKnight [2U]" if they want the split name to be "Watcher Knight [2U]"?

An alternative implementation would be to allow the user to edit the .lss output before downloading? I think that's slightly more user-friendly than having to open in a text editor?

**Comment by slaurent22** [comment]
> An alternative implementation would be to allow the user to edit the .lss output before downloading? I think that's slightly more user-friendly than having to open in a text editor?

This seems like the best quick win until we revamp the ui. We can add a toggle to make the lss output editable. (I don't want it editable by default to avoid accidental corruption)

**Comment by rixx** [comment]
Do you think it would be useful to change the serialisation format to optionally allow this too, so even presets could include changed split names? Could be just an optional mapping between split name and label, without breaking compatibility. Or is that too much change for too little payoff?

**Comment by slaurent22** [comment]
> 
> 
> Do you think it would be useful to change the serialisation format to optionally allow this too, so even presets could include changed split names? Could be just an optional mapping between split name and label, without breaking compatibility. Or is that too much change for too little payoff?

I think it's low return on investment at this point

**Comment by slaurent22** [comment]
The change is live on https://hksplitmaker.com/

I'm going to close this issue. Between this option and editing the splits within livesplit, there should be a suitable workflow for most people at this point

**Comment by slaurent22** [comment]
better functionality is now live; see https://github.com/slaurent22/hk-split-maker/issues/24
