### ISSUE TITLE
New splits use `RealTime` as comparison

### ISSUE THREAD

**Issue by cerpintext** [slaurent22/hk-split-maker#23]
It doesn't look like splits have any field for setting default comparison right off the bat.
One alternative hacky workaround to that could be to automate the 'server' machine to:
- open a livesplit instance
- open the new splits after creating
- 'manually' select `GameTime` in that instance (api call?)
- save the splits
- send this as the newly created split file to the user

This obviously isn't optimal, or necessarily very robust, but could potentially be an option still.
Another option could be scouring the livesplit code to see if there's a way to implement it straight into the lss file,
but if there's not then even a PR adding that would likely stay ignored by the official livesplit repo at least.

**Comment by rixx** [comment]
> send this as the newly created split file to the user

Does this work? How?

If it changes the lss file, we should be able to make the same change ourselves. If it doesn't change the file (and instead livesplit just has an internal cache for remembering preferred comparison modes), then online use of livesplit wouldn't help either, unless I'm missing something?

**Comment by slaurent22** [comment]
I tested: setting Compare Against does not affect the contents of the lss file. I've added a note in the instructions: https://github.com/slaurent22/hk-split-maker/commit/7673f193ef7e86f9ef0dc81be5b556e807266795
