### ISSUE TITLE
Add Link Connecting to HKSM Github

### ISSUE THREAD

**Issue by thundar001** [slaurent22/hk-split-maker#26]
Add link to the HKSM Github on the HKSM site page. Allowing for easy reference for those who would like to contribute

**Comment by rixx** [comment]
Do we want the link in the text somewhere, or in a footer, or one of those corner octocats?

**Comment by thundar001** [comment]
Let's have it as a link in text. We could have it be a notification bar at the top of the page letting people know that they can contribute. That way can quick and easy to find. Probably when there is more built up on the site and less that needs to be done we could have the link posted in a footer or the corner octocat.

**Comment by slaurent22** [comment]
#42 implemented this
