### ISSUE TITLE
rename reusable splits (suggest array when duplicate key detected in names)

### ISSUE THREAD

**Issue by cerpintext** [slaurent22/hk-split-maker#35]
while setting up 106% splits to PR, I encountered a bug where I couldn't rename two different instances of the same transition autosplit to reflect the different points in the route they represent, leading to less immediately understandable splits.

Example of how the naming was written, and the error message:
```
  "names": {
    "EnterAnyDream": "Tyrant Dream Entry",

    "EnterAnyDream": "[2d] FC Dream Entry",
```
![image](https://user-images.githubusercontent.com/27957371/128579633-1fd26a3b-ba09-4594-a57b-021ddb95bfc7.png)

**Comment by cerpintext** [comment]
this duplicate error resulted in only the second given name being used for both instances of "EnterAnyDream", as shown quick here in the output file:
![image](https://user-images.githubusercontent.com/27957371/128579873-de1d6e8f-6eec-406a-8e1d-c42f38c1a2fc.png)

**Comment by slaurent22** [comment]
Use an array of names, like the flame splits in https://hksplitmaker.com/#NKG_flame_splits

**Comment by cerpintext** [comment]
add this to the error message/suggested solution when duplicate keys in `names`? 👀

**Comment by slaurent22** [comment]
> add this to the error message/suggested solution when duplicate keys in `names`? 👀

I don't know if this is possible at the schema level, but doing it after clicking "Generate" might work with something like https://www.npmjs.com/package/json-duplicate-key-handle

**Comment by slaurent22** [comment]
Closing due to not having an action item
