### ISSUE TITLE
add sample configs to the UI

### ISSUE THREAD

**Issue by slaurent22** [slaurent22/hk-split-maker#4]
add a [`<select>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) element to the UI where you can choose different sample configs

sample configs should come from the [sample-configs/](https://github.com/slaurent22/hk-split-maker/tree/main/sample-configs) directory and imported into the source code. if performance is an issue we can dynamic import like we have with icons.json today

optionally, group these by main board / meme board / mods board

**Comment by slaurent22** [comment]
cc @rixx

**Comment by rixx** [comment]
I played around with this a little bit. It's not ready for merging into main, as it's in my playground branch, but you can see it [here](https://rixx.de/hk-split-maker/).

**Comment by slaurent22** [comment]
#17
