### ISSUE TITLE
improve performance of icon data loading

### ISSUE THREAD

**Issue by slaurent22** [slaurent22/hk-split-maker#5]
Currently we have 350 different image blobs stored in [https://github.com/slaurent22/hk-split-maker/blob/main/src/asset/icons.json]. Creating a split downloads the full set.

Proposal
1. Split the map into two maps: one mapping autosplit name to image id, and another mapping image id to image data blob. This will allow us to remove 45 extra copies of the grub icon, for instance.
2. Split the image id -> image blob data map further into chunks, e.g. skill-icons.json, boss-icons.json

So the end result might look like:
- `asset/icons.json`

```json
{
    "RescuedGrub1":  {
        "file": "misc-icons.json",
        "image-id": "Grub"
    },
    "RescuedGrub2":  {
        "file": "misc-icons.json",
        "image-id": "Grub"
    },
}
```

- `asset/misc-icons.json`
```json
{
    "Grub": "AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJ ... ",
}
```

**Comment by rixx** [comment]
I can do the data splitting, not sure I'll figure out the lazy loading for it.

**Comment by slaurent22** [comment]
I didn't want to close this until the change is deployed!

**Comment by slaurent22** [comment]
The change is live~!
