### ISSUE TITLE
meta headers / SEO

### ISSUE THREAD

**Issue by slaurent22** [slaurent22/hk-split-maker#56]
add meta headers so that apps like discord and search engines can pull in a title and description.

default page should have a generic description. category pages should have the category name in the description

hopefully this will help SEO as well. if someone Googles "hollow knight any percent splits", we'd want to surface hksplitmaker.com/#any

**Comment by rixx** [comment]
We can't do the second part right now, since the fragment (`#`) part of a URL is entirely client-side, and thus not indexed as a separate site.

I think it would generally be better if we moved from fragment paths to full paths, so `hksplitmaker.com/any` etc, while of course staying backwards compatible. We can still keep everything else the same, only that we set url.path and read it to see what we should display.

**Comment by slaurent22** [comment]
I also like the idea of having proper urls. I wonder if they should be like `hksplitmaker.com/category/any`

**Comment by rixx** [comment]
Upside: more future proof, downside: more to type? Or put categories at `/<name>` and potential future pages behind `/meta/…`.

**Comment by rixx** [comment]
Also, I'll just dump my default snippet to add discord/twitter embeds here to save some research – some information is duplicated to assure compatibility with all players. There area a lot more attributes you can add, but these usually work well.

```html
<meta name="twitter:card" content="summary" /> <!-- one of “summary" or, “summary_large_image” usually -->
<meta name="twitter:site" content="@nickname" />
<meta name="twitter:title" content="Site Title" />
<meta name="twitter:image" content="https://full.icon.url" />

<meta property="og:url" content="https://full.canonical.url" />
<meta property="og:title" content="Site Title" />
<meta property="og:description" content="Longer description, can contain call to action if you don't mind looking like you're selling stuff" />
<meta property="og:image" content="https://full.icon.url" />
```

**Comment by slaurent22** [comment]
I've added meta headers. We can revist better urls at a later time
