### ISSUE TITLE
Use `babel-loader` and `@babel/preset-env` to create polyfills

### ISSUE THREAD

**Issue by Clazex** [slaurent22/hk-split-maker#80]
Some recent JS features, e.g. [String.prototype.matchAll](https://kangax.github.io/compat-table/es2016plus/#test-String.prototype.matchAll), which is introduced in ES2020, is used [here](https://github.com/slaurent22/hk-split-maker/blob/4c5b9c08a76de26aad5f2e5b27b8676144932279/src/lib/hollowknight-splits.ts#L106), thus some browsers cannot open the page. Use babel to create polyfills for these functions.

**Comment by slaurent22** [comment]
Thanks for flagging this! The tsconfig has a target of es5 so I'm surprised. I can check the compiled output later tonight. In the meantime, could you tell me in what version of what browser you saw the issue?

**Comment by CuteReimu** [comment]
> Thanks for flagging this! The tsconfig has a target of es5 so I'm surprised. I can check the compiled output later tonight. In the meantime, could you tell me in what version of what browser you saw the issue?

My browser is QQBrowser/10.8.4552.400

Here is the error message:
```
Uncaught TypeError: splits.matchAll is not a function
at parseSplitsDefinitions (hollowknight-splits.ts?19bd:106)
at eval (splits.schema.ts?0152:4)
at Object.73707 (index.bundle.js:1)
at __webpack_require__ (index.bundle.js:1)
at index.bundle.js:1
at index.bundle.js:1
```
https://github.com/slaurent22/hk-split-maker/blob/4c5b9c08a76de26aad5f2e5b27b8676144932279/src/lib/hollowknight-splits.ts#L105-L107

**Comment by Clazex** [comment]
TS never creates polyfills, `target` and `lib` only control syntax things.

**Comment by slaurent22** [comment]
oh heck, thank you for the info! I can fix this later tonight (eastern time)

**Comment by slaurent22** [comment]
I put up the potential change in #80 but the page fails to do anything with this error
```
Uncaught ReferenceError: regeneratorRuntime is not defined
```

I'm too tired tonight to dig more into babel's documentation to figure this out. If anyone has experience with this, I'd happily take your suggestions!

**Comment by Clazex** [comment]
Babel's polyfills are [provided by `core-js`](https://babeljs.io/docs/en/babel-preset-env#usebuiltins). [Example](https://github.com/Clazex/ts-babel-rollup-boilerplate)

**Comment by Clazex** [comment]
Done in #82
